// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNrsAxL937GmPwJoo2qr8UlXVX3xvEzNg',
    appId: '1:109029294892:web:c648a02dd7e584c9a26289',
    messagingSenderId: '109029294892',
    projectId: 'trading-flutter-app',
    authDomain: 'trading-flutter-app.firebaseapp.com',
    storageBucket: 'trading-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAvQpJuO8KJVpPz6cNVk3YB0OmhRT2_44',
    appId: '1:109029294892:android:55bf62ab8847b7d8a26289',
    messagingSenderId: '109029294892',
    projectId: 'trading-flutter-app',
    storageBucket: 'trading-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeNudlixsE_1yFWz5d4pILaSBPXHdo4M',
    appId: '1:109029294892:ios:4d668b943a6fd9f6a26289',
    messagingSenderId: '109029294892',
    projectId: 'trading-flutter-app',
    storageBucket: 'trading-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.trading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHeNudlixsE_1yFWz5d4pILaSBPXHdo4M',
    appId: '1:109029294892:ios:4d668b943a6fd9f6a26289',
    messagingSenderId: '109029294892',
    projectId: 'trading-flutter-app',
    storageBucket: 'trading-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.trading',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNrsAxL937GmPwJoo2qr8UlXVX3xvEzNg',
    appId: '1:109029294892:web:88be7b6d4bccb059a26289',
    messagingSenderId: '109029294892',
    projectId: 'trading-flutter-app',
    authDomain: 'trading-flutter-app.firebaseapp.com',
    storageBucket: 'trading-flutter-app.firebasestorage.app',
  );
}
