name: Flutter CI

on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test test/unit/convert_symbol_test.dart

      - name: Run widget tests
        run: flutter test test/dashboard_test.dart

  create-and-merge-pr:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto PR develop → main"
          title: "Auto PR: develop → main"
          body: |
            PR automatically opened from develop to main after successful tests.
          base: main
          branch: develop
          delete-branch: false

      - name: Enable auto-merge if PR was created
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
