name: Flutter Web → Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests (no-bloquant)
        run: flutter test
        continue-on-error: true 

      - name: Enable Flutter web support & build
        run: |
          flutter config --enable-web
          flutter build web --release

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
