name: Flutter CI

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.19.6'
      - run: flutter pub get
      - run: flutter test test/unit/convert_symbol_test.dart
      - run: flutter test test/dashboard_test.dart

  create_pr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create PR develop → main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Merge develop into main (auto)'
          base: main
          branch: auto/pr-develop-to-main
